source: "_source"
destination: "_site"
permalink : /blerg/:categories/:title
timezone : Australia/Melbourne
markdown: kramdown
highlighter : rouge
paginate_path: "/blerg/page:num/"
exclude: ["*.scss", "theme/mohawk/scripts/"]


defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "mohawk/blog-detail"
      body__class: "standard"
